
function toggleAlert(rem, add){
	$('.loginAlert').removeClass('alert-'+ rem);
	$('.loginAlert').addClass('alert-'+ add);
}

$('.launchLogin').click(function() {
	var login = $('.login');
	var email = $('.email');
	var authCode = $('.authCode');
	var alert = $('.loginAlert');
	console.log('Begining login..');
	$('.launchLogin').html('Cancel Login');
	$('.loginBar').slideDown();
	email.focus();

		login.click(function(){
			toggleAlert('error','info');
			console.log('CHECK EMAIL');
			//Ask database if this is an email
			var userEmail = email.val();
			console.log('email '+userEmail);
			$.ajax({
			  	  url: 'auth.php',
			  	  type: "POST",
			  	  data: {email: userEmail},
			  	  success: function(result) {
			  	  	if(result === "No Email Found"){
			  	  		console.log('bad email');
			  	  		toggleAlert('info','error');
			  	  		alert.html("Looks like you aren't registered, or your email was incorrect.<br>Would you like to <a href='register.php'>register now?</a>");
			  	  		email.val("");
			  	  	}
			  	  	else{
			  	  	console.log('email good');
			  	    var userInfo = jQuery.parseJSON(result);
			  	    var gauthID = userInfo.gauthID;
			  	    console.log('ID='+gauthID);
			  	    alert.html('Enter the verfication code generated by Google Authenticator');
			  	    authCode.css('visibility','visible');
			  	    authCode.focus();
			  	    login.animate({left: "0"});

			  	    login.unbind("click").click(function(){
			  	    	toggleAlert('error','info');
			  	    	$('.loginForm').slideUp();
			  	    	console.log('CHECK AUTH');
						alert.html('Processing<span class="ellipsis">...</span>');
			  	    	var userAuth = authCode.val();
			  	    	console.log(gauthID+"-"+userAuth);
			  	    	if(isNaN(authCode) && userAuth.length != 6){
			  	    		console.log('invaild auth code'+userAuth.length);
			  	    		toggleAlert('info', 'error');
			  	    		alert.html('That\'s not a valid authentication code.');
			  	    		$('.loginForm').slideDown();
			  	    		authCode.focus();
			  	    		authCode.val("");
			  	    	}
			  	    	else {
			  	    	$.ajax({
			  	    	  	  url: 'auth.php',
			  	    	  	  type: "POST",
			  	    	  	  data: {auth: userAuth, uniqID: gauthID},
			  	    	  	  success: function(result) {
			  	    	  	  	console.log(result);
			  	    	  	  	if(result === "1"){
			  	    	  	  		//login user
			  	    	  	  		console.log("authenticated");
			  	    	  	  		toggleAlert('info','success');
			  	    	  	  		alert.html("Successfully Authenticated!");
			  	    	  	  	}
			  	    	  	  	else{
			  	    	  	  		console.log('bad auth code');
			  	    	  	  		toggleAlert('info', 'error');
			  	    	  	  		alert.html('Authentication code was incorrect.');
			  	    	  	  		$('.loginForm').slideDown();
			  	    	  	  		authCode.focus();
			  	    	  	  		authCode.val("");
			  	    	  	  	}
			  	    	  	  }
			  	    	  	}); }
			  	    	});//click
			  	}
			  	  }
			  	});
			});





	//Check authcode



	});