
function toggleAlert(rem, add){
	$('.loginAlert').removeClass('alert-'+ rem);
	$('.loginAlert').addClass('alert-'+ add);
}

$('.launchLogin').click(function() {
	var login = $('.login');
	var email = $('.email');
	var authCode = $('.authCode');
	var alert = $('.loginAlert');
	console.log('Launching login form.');
	$('.launchLogin').html('Cancel Login');
	$('.loginBar').slideDown();
	email.focus();


	$('.email').keydown(function(event){    
	    if(event.keyCode==13){
	    	console.log('Enter pressed, triggering email check.');
	    	login.trigger('click');
	    }
	});

		login.click(function(){
			toggleAlert('error','info');
			console.log('%c-- BEGIN EMAIL CHECK --', "color: blue;");
			//Ask database if this is an email
			var userEmail = email.val();
			console.log('User\'s email is: '+userEmail);
			$.ajax({
			  	  url: 'auth.php',
			  	  type: "POST",
			  	  data: {email: userEmail},
			  	  success: function(result) {
			  	  	if(result === "No Email Found"){
			  	  		console.log('%cEmail not found in DB', "color: firebrick;");
			  	  		toggleAlert('info','error');
			  	  		alert.html("Looks like you aren't registered, or your email was incorrect.<br>Would you like to <a href='register.php'>register now?</a>");
			  	  		email.val("");
			  	  	}
			  	  	else{
			  	  	console.log('Email found in DB');
			  	    var userInfo = jQuery.parseJSON(result);
			  	    var gauthID = userInfo.gauthID;
			  	    console.log('GAuthID: '+gauthID);
			  	    alert.html('Enter the verfication code generated by Google Authenticator');
			  	    authCode.css('visibility','visible');
			  	    authCode.focus();
			  	    login.animate({left: "0"});



			  	    $('.authCode').keydown(function(event){    
			  	        if(event.keyCode==13){
			  	           console.log('Enter pressed, triggering auth check.');
			  	           login.trigger('click');
			  	        }
			  	    });

			  	    login.unbind("click").click(function(){
			  	    	toggleAlert('error','info');
			  	    	$('.loginForm').slideUp();
			  	    	console.log('%c-- BEGIN AUTH CHECK --', "color: blue;");
						alert.html('Processing<span class="ellipsis">...</span>');
			  	    	var userAuth = authCode.val();
			  	    	console.log("User's GAuth ID - Auth Code: "+gauthID+"-"+userAuth);
			  	    	if(isNaN(authCode) && userAuth.length != 6){
			  	    		console.log('%cInvalid auth code. Length: '+userAuth.length, "color: firebrick;");
			  	    		toggleAlert('info', 'error');
			  	    		alert.html('That\'s not a valid authentication code.');
			  	    		$('.loginForm').slideDown();
			  	    		authCode.focus();
			  	    		authCode.val("");
			  	    	}
			  	    	else {
			  	    	$.ajax({
			  	    	  	  url: 'auth.php',
			  	    	  	  type: "POST",
			  	    	  	  data: {auth: userAuth, uniqID: gauthID},
			  	    	  	  success: function(result) {
			  	    	  	  	console.log('GAuthify returned: "'+result+'"');
			  	    	  	  	if(result === "1"){
			  	    	  	  		//login user
			  	    	  	  		console.log("It's good! Authenticating user.");
			  	    	  	  		toggleAlert('info','success');
			  	    	  	  		alert.html("Successfully Authenticated!");
			  	    	  	  	}
			  	    	  	  	else{
			  	    	  	  		console.log('%cAuth code incorrect.', "color: firebrick;");
			  	    	  	  		toggleAlert('info', 'error');
			  	    	  	  		alert.html('Authentication code was incorrect.');
			  	    	  	  		$('.loginForm').slideDown();
			  	    	  	  		authCode.focus();
			  	    	  	  		authCode.val("");
			  	    	  	  	}
			  	    	  	  }
			  	    	  	}); }
			  	    	});//click
			  	}
			  	  }
			  	});
			});





	//Check authcode



	});