
$('.launchLogin').click(function() {
	var login = $('.login');
	var email = $('.email');
	var authCode = $('.authCode');
	var alert = $('.loginAlert');
	console.log('Begining login..');
	$('.launchLogin').html('Cancel Login');
	$('.loginBar').slideDown();
	email.focus();
	//Ask database if this is an email


	
	login.click(function(){
		//If email checks out
		console.log("email's good");
		alert.html('Enter the verfication code generated by Google Authenticator')
		authCode.css('visibility','visible');
		authCode.focus();
		login.animate({left: "0"});


		login.click(function(){
			$('.loginForm').slideUp();
			alert.html('Processing');
		});


	});



});